### ISSUE TITLE
Does http4k work for android 

### ISSUE THREAD

**Issue by rizwanrazi** [http4k/http4k#711] opened 2022-03-17 06:36 UTC
I am using the following dependencies in my android project. 

`  implementation platform("org.http4k:http4k-bom:4.21.1.1")
 implementation "org.http4k:http4k-core"
    implementation "org.http4k:http4k-server-undertow"
    implementation "org.http4k:http4k-client-apache"`

When I am running at compile time, I am getting error 

Duplicate class javax.servlet.AsyncContext found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)

`Duplicate class javax.servlet.AsyncContext found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.AsyncEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.AsyncListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.DispatcherType found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.Filter found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.FilterChain found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.FilterConfig found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.FilterRegistration found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.FilterRegistration$Dynamic found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.GenericFilter found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.GenericServlet found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.HttpConstraintElement found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.HttpMethodConstraintElement found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.MultipartConfigElement found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ReadListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.Registration found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.Registration$Dynamic found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.RequestDispatcher found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.Servlet found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletConfig found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContainerInitializer found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContext found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContextAttributeEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContextAttributeListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContextEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletContextListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletException found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletInputStream found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletOutputStream found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRegistration found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRegistration$Dynamic found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequest found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequestAttributeEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequestAttributeListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequestEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequestListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletRequestWrapper found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletResponse found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletResponseWrapper found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.ServletSecurityElement found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.SessionCookieConfig found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.SessionTrackingMode found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.SingleThreadModel found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.UnavailableException found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.WriteListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.HandlesTypes found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.HttpConstraint found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.HttpMethodConstraint found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.MultipartConfig found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.ServletSecurity found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.ServletSecurity$EmptyRoleSemantic found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.ServletSecurity$TransportGuarantee found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.WebFilter found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.WebInitParam found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.WebListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.annotation.WebServlet found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.descriptor.JspConfigDescriptor found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.descriptor.JspPropertyGroupDescriptor found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.descriptor.TaglibDescriptor found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.Cookie found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpFilter found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServlet found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletMapping found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletRequest found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletRequest$1 found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletRequestWrapper found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletResponse found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpServletResponseWrapper found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSession found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionActivationListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionAttributeListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionBindingEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionBindingListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionContext found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionEvent found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionIdListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpSessionListener found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpUpgradeHandler found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.HttpUtils found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.MappingMatch found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.NoBodyOutputStream found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.NoBodyResponse found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.Part found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.PushBuilder found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)
Duplicate class javax.servlet.http.WebConnection found in modules jetified-javax.servlet-api-4.0.1 (javax.servlet:javax.servlet-api:4.0.1) and jetified-jboss-servlet-api_4.0_spec-2.0.0.Final (org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final)

Go to the documentation to learn how to Fix dependency resolution errors.
`

**Comment by s4nchez** [comment] 2022-03-17 08:08
Hi @rizwanrazi. 

We don't test http4k libraries in Android so there are no guarantees things will work there. 

Have you tried starting just with `http4k-core` to see if it works? You should be able to make HTTP calls and spin up a server just with that.

**Comment by rizwanrazi** [comment] 2022-03-17 08:33
These two (implementation platform("org.http4k:http4k-bom:4.21.1.1")
    implementation "org.http4k:http4k-core") I am able to run and not doing any issue at compile time. But these two not able to compile until now ... ( implementation "org.http4k:http4k-server-undertow"
    implementation "org.http4k:http4k-client-apache")

**Comment by s4nchez** [comment] 2022-03-17 09:05
That's the issue: those modules depend on underlying non-http4k libraries (apache client/undertow) and we don't keep track if they work on Android. 

You're probably better off looking at those projects to find out how to set them up for Android. The http4k integration libraries `http4k-server-xyz` and `http4k-client-xyz` are a simple abstraction layer that shouldn't be a problem in this case.

**Comment by rizwanrazi** [comment] 2022-03-18 08:00
I am able to compile it finally. at run time facing issue now...

`2022-03-18 02:00:01.183 26711-26711/com.test.http4kexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.http4kexample, PID: 26711
    java.lang.NoSuchMethodError: No virtual method staticFieldBase(Ljava/lang/reflect/Field;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-oj.jar)
        at org.jboss.threads.EnhancedQueueExecutor.<clinit>(EnhancedQueueExecutor.java:295)
        at org.xnio.XnioWorker.<init>(XnioWorker.java:139)
        at org.xnio.nio.NioXnioWorker.<init>(NioXnioWorker.java:84)
        at org.xnio.nio.NioXnio.build(NioXnio.java:232)
        at org.xnio.XnioWorker$Builder.build(XnioWorker.java:1191)
        at org.xnio.Xnio.createWorker(Xnio.java:481)
        at org.xnio.Xnio.createWorker(Xnio.java:463)
        at org.xnio.Xnio.createWorker(Xnio.java:450)
        at io.undertow.Undertow.start(Undertow.java:125)
        at org.http4k.server.Undertow$toServer$1.start(Undertow.kt:40)
        at org.http4k.server.Undertow$toServer$1.start(Undertow.kt:34)
        at com.test.http4kexample.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-03-18 02:00:01.192 26711-26711/com.test.http4kexample I/Process: Sending signal. PID: 26711 SIG: 9`

**Comment by s4nchez** [comment] 2022-03-18 08:32
Unfortunately, again, that seems like a problem in Undertow which, frankly I don't even know if supports Android in the first place.

I'll close this now but feel free to reopen if you have reason to believe the problem is on the http4k side.

**Closed by s4nchez** 2022-03-18 08:32 UTC
