### ISSUE TITLE
Java8HttpClient causes SignatureDoesNotMatch exception on S3Bucket.copyObject() request

### ISSUE THREAD

**Issue by obecker** [http4k/http4k#1048] opened 2024-02-02 19:45 UTC
I'm using the latest versions of `http4k-core` and `http4k-connect-amazon-s3` with Java 17 in an AWS Lambda function.

Because of Andrew's [blog article](https://betterprogramming.pub/faster-kotlin-apis-on-aws-lambda-8694649bf9dd) I have used the `Java8HttpClient` for performing requests to AWS (DynamoDB and now S3). Until now this worked quite well. However, performing an `S3Bucket.copyObject()` request fails with a `SignatureDoesNotMatch` exception. Other bucket requests like `putObject`, `getObject`, and `deleteObject` are executed without problems. So it might be that the extra header `x-amz-copy-source` is causing this.

I'm creating this issue here in the http4k core project (and not in [http4k-connect](https://github.com/http4k/http4k-connect)) because with the default `JavaHttpClient` the error is gone. So it's probably not a very urgent issue and I don't know how easy it is to fix.

----

Example code:
```kotlin
val credentialsProvider = ...
val region = ...
val bucketName = ...

val s3 = S3.Http(credentialsProvider)
s3.createBucket(bucketName, region)

// => using `http = JavaHttpClient()` here fixes the issue
val s3Bucket = S3Bucket.Http(bucketName, region, credentialsProvider, http = Java8HttpClient().debug())

val key = BucketKey.of("my/current/key")
s3Bucket.putObject(key, "file content".byteInputStream()).onFailure { it.reason.throwIt() }

val newKey = BucketKey.of("my/new/key")
s3Bucket.copyObject(bucketName, key, newKey).onFailure { it.reason.throwIt() } // => SignatureDoesNotMatch
```

**Comment by daviddenton** [comment] 2024-02-02 20:07
Running both clients against the running FakeS3, we can see that if we use the Java 11 client, for copy object we get:

```
***** REQUEST: PUT: /end *****
PUT /end HTTP/1.1
X-amz-copy-source: foobar/start
Host: localhost:8000
User-agent: Java-http-client/21.0.1
Authorization: AWS4-HMAC-SHA256 Credential=accessKeyId/19700101/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-forwarded-host, Signature=c2167caae596e4716f9d821430c22127876f7b9d119cc4aa5347a93d9cb47858
X-forwarded-host: foobar.s3.us-east-1.amazonaws.com
X-amz-date: 19700101T000000Z
X-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Content-length: 0
```

and with the Java8 client:

```
***** REQUEST: PUT: /end *****
PUT /end HTTP/1.1
Accept: */*
Connection: keep-alive
X-amz-copy-source: foobar/start
Host: localhost:8000
User-agent: Java/21.0.1
X-forwarded-host: foobar.s3.us-east-1.amazonaws.com
Authorization: AWS4-HMAC-SHA256 Credential=accessKeyId/19700101/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-forwarded-host, Signature=c2167caae596e4716f9d821430c22127876f7b9d119cc4aa5347a93d9cb47858
X-amz-date: 19700101T000000Z
X-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

For put object, Java 11:
```
***** REQUEST: PUT: /start *****
PUT /start HTTP/1.1
Host: localhost:8000
User-agent: Java-http-client/21.0.1
Authorization: AWS4-HMAC-SHA256 Credential=accessKeyId/19700101/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date;x-forwarded-host, Signature=2e978cccfad38fedc07504546ef312a95dc6aaa73f7613c4dfe95986b6cc1f41
X-forwarded-host: foobar.s3.us-east-1.amazonaws.com
X-amz-date: 19700101T000000Z
X-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Content-length: 0
```

and Java 8:
```
***** REQUEST: PUT: /start *****
PUT /start HTTP/1.1
Accept: */*
Connection: keep-alive
Host: localhost:8000
User-agent: Java/21.0.1
Authorization: AWS4-HMAC-SHA256 Credential=accessKeyId/19700101/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date;x-forwarded-host, Signature=2e978cccfad38fedc07504546ef312a95dc6aaa73f7613c4dfe95986b6cc1f41
X-forwarded-host: foobar.s3.us-east-1.amazonaws.com
X-amz-date: 19700101T000000Z
X-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

.. so I'm actually surprised that ANY of the operations work with the Java8 client if it is due to the new headers added by java8. This leads me to think this is a quirk of the way that the S3 operations are implemented.

**Comment by oharaandrew314** [comment] 2024-02-06 20:59
AFAIK, AWS only calculates the signature based on the headers you include in the `SignedHeaders` component of the `Authorization` header.  Is that not true?

**Comment by daviddenton** [comment] 2024-02-06 21:03
That is 100% my understanding. But I'm not sure what to think here - the requests above made with the different clients to the Fake are ONLY different in those extra headers - the signature is the same as is the list of headers used. Is there something different about the copy operation which could be different? 🤷 . We can copy those requests as a curl and try them against the real thing - I suspect the result will be the same.

**Comment by obecker** [comment] 2024-02-07 07:00
Just to be sure: can you reproduce the behaviour with my example code above? Or is it caused by something else specific to my environment?

**Comment by daviddenton** [comment] 2024-02-07 12:02
No - I only recreated this problem using a fake running against the various http clients 😄

**Comment by s4nchez** [comment] 2024-02-07 12:05
@obecker I can reproduce the issue, and I suspect it has something to do with content length and how each client sends that info over the wire (i.e. after http4k converts a request into the client-specific request). Here's an example of the canonical request calculated by AWS (as returned in the `<CanonicalRequestBytes>` as part of the error:

```PUT
/my/new/key

content-length:
host:b-1048.s3.eu-west-2.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source:b-1048/my/current/key
x-amz-date:20240207T105831Z
x-forwarded-host:b-1048.s3.eu-west-2.amazonaws.com

content-length;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-forwarded-host
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855```

We'd still need further investigation into the internals of Java8HttpClient to figure out where the request is being changed, though.

**Comment by daviddenton** [comment] 2024-02-07 12:55
The thing is that the other S3 operations work with the Java8 client even though it sends the content length every time.... if you used the Java11 client and set the content length AFTER the signing, so you also get this problem?

**Comment by s4nchez** [comment] 2024-02-07 13:28
Java8 client will add `content-length` if the body length is > 0. That explains why PutObject works, but CopyObject doesn't.

**Comment by s4nchez** [comment] 2024-02-08 23:26
This client limitation has been fixed in http4k version 5.13.5.0 and propagated to http4k-connect version 5.6.12.0. I've tested with the example above, and it now works fine.

@obecker thank you for spotting + reporting this issue, and let us know if the fix worked for you :)

**Closed by s4nchez** 2024-02-08 23:26 UTC

**Comment by obecker** [comment] 2024-02-09 15:39
@s4nchez Thanks for the fix. Yes, all S3 operations are working now with the `Java8HttpClient` 😀

**Comment by oharaandrew314** [comment] 2024-02-09 20:54
Incredible work @s4nchez !
