### ISSUE TITLE
AWS Lambda Class does not implement an appropriate handler interface

### ISSUE THREAD

**Issue by webmarkyn** [http4k/http4k#559] opened 2021-01-14 19:22 UTC

**Comment by daviddenton** [comment] 2021-01-14 19:26
It doesn't need to. We deliberately removed this dependency as it's not required and we just use Maps instead for the intermediate format.

Closing this because it's not a bug. If you're having a problems with things not working then reopen and let us know. Best thing for decent responses is the Kotlin slack #http4k channel...

**Comment by webmarkyn** [comment] 2021-01-14 19:47
Sorry, last time I accidentally created an issue with no description.
I just created a new http4k project using project wizard (I have chosen serverless aws lambda).
Then created shadow jar and uploaded it to my aws lambda (handler is com.example.HelloWorldLoader) but it gives me this error.
```
{
  "errorMessage": "Class does not implement an appropriate handler interface: com.example.HelloWorldLoader"
}
```
What am I doing wrong?
Thank you for your time

build.gradle

```
buildscript {
ext.kotlinVersion = "1.4.21"
ext.http4kVersion = "4.0.0.0"

repositories {
    mavenCentral()
    jcenter()
}

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
        classpath 'com.github.jengelman.gradle.plugins:shadow:5.2.0'
    }
}

apply plugin: 'application'

mainClassName = "com.example.HelloWorldKt"
apply plugin: 'com.github.johnrengelman.shadow'

shadowJar {
    archiveBaseName.set(project.name)
    archiveClassifier.set(null)
    archiveVersion.set(null)
    mergeServiceFiles()
}

repositories {
    mavenCentral()
    jcenter()
}

apply plugin: 'kotlin'
apply plugin: 'application'

compileKotlin.kotlinOptions.jvmTarget = "11"
compileTestKotlin.kotlinOptions.jvmTarget = "11"

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

test {
    useJUnitPlatform()
}

compileTestKotlin.kotlinOptions {
    jvmTarget = "11"
}

dependencies {
    implementation "org.http4k:http4k-client-jetty:${http4kVersion}"
    implementation "org.http4k:http4k-core:${http4kVersion}"
    implementation "org.http4k:http4k-serverless-lambda:${http4kVersion}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.21"
    testImplementation "org.http4k:http4k-testing-approval:${http4kVersion}"
    testImplementation "org.http4k:http4k-testing-hamkrest:${http4kVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.7.0"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:5.7.0"
}
```

HelloWorld.kt
```
package com.example

import org.http4k.client.JettyClient
import org.http4k.core.HttpHandler
import org.http4k.core.Method.GET
import org.http4k.core.Response
import org.http4k.core.Status.Companion.OK
import org.http4k.core.Uri
import org.http4k.core.then
import org.http4k.filter.ClientFilters
import org.http4k.filter.DebuggingFilters.PrintRequest
import org.http4k.filter.DebuggingFilters.PrintResponse
import org.http4k.routing.bind
import org.http4k.routing.routes
import org.http4k.serverless.AppLoader


object HelloWorldLoader : AppLoader {
    override fun invoke(env: Map<String, String>): HttpHandler {

        val client = PrintResponse()
            .then(ClientFilters.SetBaseUriFrom(Uri.of("https://pokeapi.co/api/v2/pokemon")))
            .then(JettyClient())

        return PrintRequest()
            .then(
                routes(
                    "/pokemon" bind client,
                    "/ping" bind GET to {
                        Response(OK).body("pong")
                    }
                )
            )
    }
}

```

**Comment by daviddenton** [comment] 2021-01-14 19:57
You're almost there! Just missing the definition of the actual function itself. :) 

You need something like this:

```kotlin
class HelloWorld : ApiGatewayV2LambdaFunction(ServerForClientContract)
```

Full example is here: 
https://www.http4k.org/guide/modules/serverless/#aws_lambda_integration

**Comment by daviddenton** [comment] 2021-01-15 04:00
Apologies - I can see now that the toolbox output didn't generate the correct class. 

This is actually a bug with the http4k Toolbox so will fix over in that project.

Thanks for reporting it!

**Comment by daviddenton** [comment] 2021-01-15 15:37
This is now fixed and deployed in the toolbox. Thanks again @webmarkyn !

**Comment by daviddenton** [comment] 2021-01-15 15:37
Please let us know if you're still having trouble

**Closed by daviddenton** 2021-01-15 15:37 UTC
