### ISSUE TITLE
SLF4J and http4k-client-websocket

### ISSUE THREAD

**Issue by fintara** [http4k/http4k#360] opened 2020-01-26 10:33 UTC
Steps to reproduce:
1. add dependencies:
```
implementation(group: "org.http4k", name: "http4k-core", version: "3.226.0")
implementation(group: "org.http4k", name: "http4k-server-jetty", version: "3.226.0")
implementation(group: "org.http4k", name: "http4k-client-websocket", version: "3.226.0")
```

2. write simple main
```kotlin
fun main() {
    websockets(
        "/ws" bind { ws: Websocket -> }
    ).asServer(Jetty(8080)).start()
}
```

Output from console:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

If you remove `http4k-client-websocket` dep, then logging works.

**Comment by daviddenton** [comment] 2020-01-26 11:00
This must be a problem caused by the client that we use, as it's the only compiled dependency - here's the gradle file for that module: ```dependencies {
    provided Libs.kotlin_stdlib_jdk8
    provided project(":http4k-core")

    compile Libs.java_websocket

    testCompile project(path: ":http4k-core", configuration: "testArtifacts")
    testCompile project(path: ":http4k-server-jetty")
    testCompile Config.TestDependencies
}

```

I can see that there is a dependency on sl4j in the client gradle:
https://github.com/TooTallNate/Java-WebSocket

**Comment by fintara** [comment] 2020-01-28 13:00
> Which version of SL4J are you using (if any)?

I'm not using any directly, my only dependencies are these 3 + kotlin stdlib.

As per [StackOverflow](https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder), adding `compile "org.slf4j:slf4j-simple:1.7.25"` to `http4k-client-websocket/build.gradle` solves the problem. Might be better to replace [`compile` with `implementation`](https://stackoverflow.com/a/44493379/1365831) in this case.

**Comment by daviddenton** [comment] 2020-01-28 21:24
Thanks for the PR 🙃

**Comment by joscha-alisch** [comment] 2020-01-28 21:34
Correct me if I'm wrong, but wouldn't this change now force everyone to use the "slf4j-simple" logging implementation? I believe slf4j also prints out warnings if you have multiple implementations on the classpath.

I'd say it would be better to let the users decide which implementation they want to use instead of "vendoring" this one. Thoughts?

**Comment by daviddenton** [comment] 2020-01-28 21:38
@joscha-alisch Good point. Thanks for noticing! I'll open this up again to track. 😄

**Comment by fintara** [comment] 2020-01-29 10:18
Sorry about that. So in the end I'd have to add this dep to my project, even if I don't use it directly?

**Comment by daviddenton** [comment] 2020-01-31 20:49
Yep - it's quite an annoying warning TBH, but we do want to avoid having a dependency on any implementation, so closing this unless we think there's anything else to add. :)

**Closed by daviddenton** 2020-01-31 20:49 UTC
